      
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: miapp_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: miapp
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: miapp_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@colegio.com
      PGADMIN_DEFAULT_PASSWORD: admin123

volumes:
  postgres_data:
